// <auto-generated />
using System;
using Flooq.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
  [DbContext(typeof(FlooqContext))]
  partial class FlooqContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.3")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Flooq.Model.DataFlow", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid");

            b.Property<string>("Definition")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("DataFlows");
          });

      modelBuilder.Entity("Flooq.Model.Version", b =>
          {
            b.Property<string>("Tag")
                      .HasColumnType("text");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Notes")
                      .IsRequired()
                      .HasColumnType("text");

            b.HasKey("Tag");

            b.ToTable("Versions");
          });
#pragma warning restore 612, 618
    }
  }
}
